application: appengine-git
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /[A-Za-z0-9]+.git/.*
  script: git_http_protocol.app

- url: /.*
  script: main.app